name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o recx-linux-amd64
          GOOS=windows GOARCH=amd64 go build -o recx-windows-amd64.exe
          GOOS=darwin GOARCH=amd64 go build -o recx-darwin-amd64
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            recx-linux-amd64
            recx-windows-amd64.exe
            recx-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
